// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workspaceRouteImport } from "./routes/_workspace";
import { Route as indexRouteImport } from "./routes/index";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as workspaceDotreposRouteImport } from "./routes/_workspace.repos";
import { Route as workspaceDotchannelsRouteImport } from "./routes/_workspace.channels";
import { Route as workspaceDotchannelsDotchannelIdRouteImport } from "./routes/_workspace.channels.$channelId";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const workspaceRoute = workspaceRouteImport.update({
  id: "/_workspace",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const workspaceDotreposRoute = workspaceDotreposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotchannelsRoute = workspaceDotchannelsRouteImport.update({
  id: "/channels",
  path: "/channels",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotchannelsDotchannelIdRoute =
  workspaceDotchannelsDotchannelIdRouteImport.update({
    id: "/channels/$channelId",
    path: "/channels/$channelId",
    getParentRoute: () => workspaceRoute,
  } as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/channels": typeof workspaceDotchannelsRoute;
  "/repos": typeof workspaceDotreposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/channels/$channelId": typeof workspaceDotchannelsDotchannelIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/channels": typeof workspaceDotchannelsRoute;
  "/repos": typeof workspaceDotreposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/channels/$channelId": typeof workspaceDotchannelsDotchannelIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/_workspace": typeof workspaceRouteWithChildren;
  "/_workspace/channels": typeof workspaceDotchannelsRoute;
  "/_workspace/repos": typeof workspaceDotreposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/_workspace/channels/$channelId": typeof workspaceDotchannelsDotchannelIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/channels"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/channels/$channelId"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/channels"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/channels/$channelId"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/_workspace"
    | "/_workspace/channels"
    | "/_workspace/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/_workspace/channels/$channelId"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  workspaceRoute: typeof workspaceRouteWithChildren;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_workspace": {
      id: "/_workspace";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof workspaceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_workspace/repos": {
      id: "/_workspace/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof workspaceDotreposRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/channels": {
      id: "/_workspace/channels";
      path: "/channels";
      fullPath: "/channels";
      preLoaderRoute: typeof workspaceDotchannelsRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/channels/$channelId": {
      id: "/_workspace/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof workspaceDotchannelsDotchannelIdRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface workspaceRouteChildren {
  workspaceDotchannelsRoute: typeof workspaceDotchannelsRoute;
  workspaceDotreposRoute: typeof workspaceDotreposRoute;
  workspaceDotchannelsDotchannelIdRoute: typeof workspaceDotchannelsDotchannelIdRoute;
}

const workspaceRouteChildren: workspaceRouteChildren = {
  workspaceDotchannelsRoute: workspaceDotchannelsRoute,
  workspaceDotreposRoute: workspaceDotreposRoute,
  workspaceDotchannelsDotchannelIdRoute: workspaceDotchannelsDotchannelIdRoute,
};

const workspaceRouteWithChildren = workspaceRoute._addFileChildren(
  workspaceRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  workspaceRoute: workspaceRouteWithChildren,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
