// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workspaceRouteImport } from "./routes/_workspace";
import { Route as indexRouteImport } from "./routes/index";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as workspaceDotworkflowsRouteImport } from "./routes/_workspace.workflows";
import { Route as workspaceDotsavedRouteImport } from "./routes/_workspace.saved";
import { Route as workspaceDotreposRouteImport } from "./routes/_workspace.repos";
import { Route as workspaceDotremindersRouteImport } from "./routes/_workspace.reminders";
import { Route as workspaceDotpulseRouteImport } from "./routes/_workspace.pulse";
import { Route as workspaceDotpeopleRouteImport } from "./routes/_workspace.people";
import { Route as workspaceDotmessagesRouteImport } from "./routes/_workspace.messages";
import { Route as workspaceDothomeRouteImport } from "./routes/_workspace.home";
import { Route as workspaceDotdraftsRouteImport } from "./routes/_workspace.drafts";
import { Route as workspaceDotdocumentsRouteImport } from "./routes/_workspace.documents";
import { Route as workspaceDotchannelsRouteImport } from "./routes/_workspace.channels";
import { Route as workspaceDotagentsRouteImport } from "./routes/_workspace.agents";
import { Route as workspaceDotdraftsDotindexRouteImport } from "./routes/_workspace.drafts.index";
import { Route as workspaceDotreposDotrepoIdRouteImport } from "./routes/_workspace.repos.$repoId";
import { Route as workspaceDotmessagesDotnewRouteImport } from "./routes/_workspace.messages.new";
import { Route as workspaceDotmessagesDotchannelIdRouteImport } from "./routes/_workspace.messages.$channelId";
import { Route as workspaceDotlenosDotsplatRouteImport } from "./routes/_workspace.lenos.$";
import { Route as workspaceDotdraftsDotscheduledRouteImport } from "./routes/_workspace.drafts.scheduled";
import { Route as workspaceDotchannelsDotchannelIdRouteImport } from "./routes/_workspace.channels.$channelId";
import { Route as workspaceDotreposDotrepoIdDotblobDotsplatRouteImport } from "./routes/_workspace.repos.$repoId.blob.$";
import { Route as workspaceDotchannelsDotchannelIdDotpostsDotpostIdRouteImport } from "./routes/_workspace.channels.$channelId.posts.$postId";

const workspaceRoute = workspaceRouteImport.update({
  id: "/_workspace",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const workspaceDotworkflowsRoute = workspaceDotworkflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotsavedRoute = workspaceDotsavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotreposRoute = workspaceDotreposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotremindersRoute = workspaceDotremindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotpulseRoute = workspaceDotpulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotpeopleRoute = workspaceDotpeopleRouteImport.update({
  id: "/people",
  path: "/people",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotmessagesRoute = workspaceDotmessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDothomeRoute = workspaceDothomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotdraftsRoute = workspaceDotdraftsRouteImport.update({
  id: "/drafts",
  path: "/drafts",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotdocumentsRoute = workspaceDotdocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotchannelsRoute = workspaceDotchannelsRouteImport.update({
  id: "/channels",
  path: "/channels",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotagentsRoute = workspaceDotagentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => workspaceRoute,
} as any);
const workspaceDotdraftsDotindexRoute =
  workspaceDotdraftsDotindexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => workspaceDotdraftsRoute,
  } as any);
const workspaceDotreposDotrepoIdRoute =
  workspaceDotreposDotrepoIdRouteImport.update({
    id: "/repos/$repoId",
    path: "/repos/$repoId",
    getParentRoute: () => workspaceRoute,
  } as any);
const workspaceDotmessagesDotnewRoute =
  workspaceDotmessagesDotnewRouteImport.update({
    id: "/messages/new",
    path: "/messages/new",
    getParentRoute: () => workspaceRoute,
  } as any);
const workspaceDotmessagesDotchannelIdRoute =
  workspaceDotmessagesDotchannelIdRouteImport.update({
    id: "/messages/$channelId",
    path: "/messages/$channelId",
    getParentRoute: () => workspaceRoute,
  } as any);
const workspaceDotlenosDotsplatRoute =
  workspaceDotlenosDotsplatRouteImport.update({
    id: "/lenos/$",
    path: "/lenos/$",
    getParentRoute: () => workspaceRoute,
  } as any);
const workspaceDotdraftsDotscheduledRoute =
  workspaceDotdraftsDotscheduledRouteImport.update({
    id: "/scheduled",
    path: "/scheduled",
    getParentRoute: () => workspaceDotdraftsRoute,
  } as any);
const workspaceDotchannelsDotchannelIdRoute =
  workspaceDotchannelsDotchannelIdRouteImport.update({
    id: "/channels/$channelId",
    path: "/channels/$channelId",
    getParentRoute: () => workspaceRoute,
  } as any);
const workspaceDotreposDotrepoIdDotblobDotsplatRoute =
  workspaceDotreposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => workspaceRoute,
  } as any);
const workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute =
  workspaceDotchannelsDotchannelIdDotpostsDotpostIdRouteImport.update({
    id: "/channels/$channelId/posts/$postId",
    path: "/channels/$channelId/posts/$postId",
    getParentRoute: () => workspaceRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agents": typeof workspaceDotagentsRoute;
  "/channels": typeof workspaceDotchannelsRoute;
  "/documents": typeof workspaceDotdocumentsRoute;
  "/drafts": typeof workspaceDotdraftsRouteWithChildren;
  "/home": typeof workspaceDothomeRoute;
  "/messages": typeof workspaceDotmessagesRoute;
  "/people": typeof workspaceDotpeopleRoute;
  "/pulse": typeof workspaceDotpulseRoute;
  "/reminders": typeof workspaceDotremindersRoute;
  "/repos": typeof workspaceDotreposRoute;
  "/saved": typeof workspaceDotsavedRoute;
  "/workflows": typeof workspaceDotworkflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/channels/$channelId": typeof workspaceDotchannelsDotchannelIdRoute;
  "/drafts/scheduled": typeof workspaceDotdraftsDotscheduledRoute;
  "/lenos/$": typeof workspaceDotlenosDotsplatRoute;
  "/messages/$channelId": typeof workspaceDotmessagesDotchannelIdRoute;
  "/messages/new": typeof workspaceDotmessagesDotnewRoute;
  "/repos/$repoId": typeof workspaceDotreposDotrepoIdRoute;
  "/drafts/": typeof workspaceDotdraftsDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute;
  "/repos/$repoId/blob/$": typeof workspaceDotreposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agents": typeof workspaceDotagentsRoute;
  "/channels": typeof workspaceDotchannelsRoute;
  "/documents": typeof workspaceDotdocumentsRoute;
  "/home": typeof workspaceDothomeRoute;
  "/messages": typeof workspaceDotmessagesRoute;
  "/people": typeof workspaceDotpeopleRoute;
  "/pulse": typeof workspaceDotpulseRoute;
  "/reminders": typeof workspaceDotremindersRoute;
  "/repos": typeof workspaceDotreposRoute;
  "/saved": typeof workspaceDotsavedRoute;
  "/workflows": typeof workspaceDotworkflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/channels/$channelId": typeof workspaceDotchannelsDotchannelIdRoute;
  "/drafts/scheduled": typeof workspaceDotdraftsDotscheduledRoute;
  "/lenos/$": typeof workspaceDotlenosDotsplatRoute;
  "/messages/$channelId": typeof workspaceDotmessagesDotchannelIdRoute;
  "/messages/new": typeof workspaceDotmessagesDotnewRoute;
  "/repos/$repoId": typeof workspaceDotreposDotrepoIdRoute;
  "/drafts": typeof workspaceDotdraftsDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute;
  "/repos/$repoId/blob/$": typeof workspaceDotreposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/_workspace": typeof workspaceRouteWithChildren;
  "/_workspace/agents": typeof workspaceDotagentsRoute;
  "/_workspace/channels": typeof workspaceDotchannelsRoute;
  "/_workspace/documents": typeof workspaceDotdocumentsRoute;
  "/_workspace/drafts": typeof workspaceDotdraftsRouteWithChildren;
  "/_workspace/home": typeof workspaceDothomeRoute;
  "/_workspace/messages": typeof workspaceDotmessagesRoute;
  "/_workspace/people": typeof workspaceDotpeopleRoute;
  "/_workspace/pulse": typeof workspaceDotpulseRoute;
  "/_workspace/reminders": typeof workspaceDotremindersRoute;
  "/_workspace/repos": typeof workspaceDotreposRoute;
  "/_workspace/saved": typeof workspaceDotsavedRoute;
  "/_workspace/workflows": typeof workspaceDotworkflowsRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/_workspace/channels/$channelId": typeof workspaceDotchannelsDotchannelIdRoute;
  "/_workspace/drafts/scheduled": typeof workspaceDotdraftsDotscheduledRoute;
  "/_workspace/lenos/$": typeof workspaceDotlenosDotsplatRoute;
  "/_workspace/messages/$channelId": typeof workspaceDotmessagesDotchannelIdRoute;
  "/_workspace/messages/new": typeof workspaceDotmessagesDotnewRoute;
  "/_workspace/repos/$repoId": typeof workspaceDotreposDotrepoIdRoute;
  "/_workspace/drafts/": typeof workspaceDotdraftsDotindexRoute;
  "/_workspace/channels/$channelId/posts/$postId": typeof workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute;
  "/_workspace/repos/$repoId/blob/$": typeof workspaceDotreposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/channels"
    | "/documents"
    | "/drafts"
    | "/home"
    | "/messages"
    | "/people"
    | "/pulse"
    | "/reminders"
    | "/repos"
    | "/saved"
    | "/workflows"
    | "/invite/$code"
    | "/channels/$channelId"
    | "/drafts/scheduled"
    | "/lenos/$"
    | "/messages/$channelId"
    | "/messages/new"
    | "/repos/$repoId"
    | "/drafts/"
    | "/channels/$channelId/posts/$postId"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/channels"
    | "/documents"
    | "/home"
    | "/messages"
    | "/people"
    | "/pulse"
    | "/reminders"
    | "/repos"
    | "/saved"
    | "/workflows"
    | "/invite/$code"
    | "/channels/$channelId"
    | "/drafts/scheduled"
    | "/lenos/$"
    | "/messages/$channelId"
    | "/messages/new"
    | "/repos/$repoId"
    | "/drafts"
    | "/channels/$channelId/posts/$postId"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/_workspace"
    | "/_workspace/agents"
    | "/_workspace/channels"
    | "/_workspace/documents"
    | "/_workspace/drafts"
    | "/_workspace/home"
    | "/_workspace/messages"
    | "/_workspace/people"
    | "/_workspace/pulse"
    | "/_workspace/reminders"
    | "/_workspace/repos"
    | "/_workspace/saved"
    | "/_workspace/workflows"
    | "/invite/$code"
    | "/_workspace/channels/$channelId"
    | "/_workspace/drafts/scheduled"
    | "/_workspace/lenos/$"
    | "/_workspace/messages/$channelId"
    | "/_workspace/messages/new"
    | "/_workspace/repos/$repoId"
    | "/_workspace/drafts/"
    | "/_workspace/channels/$channelId/posts/$postId"
    | "/_workspace/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  workspaceRoute: typeof workspaceRouteWithChildren;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_workspace": {
      id: "/_workspace";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof workspaceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_workspace/workflows": {
      id: "/_workspace/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workspaceDotworkflowsRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/saved": {
      id: "/_workspace/saved";
      path: "/saved";
      fullPath: "/saved";
      preLoaderRoute: typeof workspaceDotsavedRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/repos": {
      id: "/_workspace/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof workspaceDotreposRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/reminders": {
      id: "/_workspace/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof workspaceDotremindersRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/pulse": {
      id: "/_workspace/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof workspaceDotpulseRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/people": {
      id: "/_workspace/people";
      path: "/people";
      fullPath: "/people";
      preLoaderRoute: typeof workspaceDotpeopleRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/messages": {
      id: "/_workspace/messages";
      path: "/messages";
      fullPath: "/messages";
      preLoaderRoute: typeof workspaceDotmessagesRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/home": {
      id: "/_workspace/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof workspaceDothomeRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/drafts": {
      id: "/_workspace/drafts";
      path: "/drafts";
      fullPath: "/drafts";
      preLoaderRoute: typeof workspaceDotdraftsRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/documents": {
      id: "/_workspace/documents";
      path: "/documents";
      fullPath: "/documents";
      preLoaderRoute: typeof workspaceDotdocumentsRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/channels": {
      id: "/_workspace/channels";
      path: "/channels";
      fullPath: "/channels";
      preLoaderRoute: typeof workspaceDotchannelsRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/agents": {
      id: "/_workspace/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof workspaceDotagentsRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/drafts/": {
      id: "/_workspace/drafts/";
      path: "/";
      fullPath: "/drafts/";
      preLoaderRoute: typeof workspaceDotdraftsDotindexRouteImport;
      parentRoute: typeof workspaceDotdraftsRoute;
    };
    "/_workspace/repos/$repoId": {
      id: "/_workspace/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof workspaceDotreposDotrepoIdRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/messages/new": {
      id: "/_workspace/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof workspaceDotmessagesDotnewRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/messages/$channelId": {
      id: "/_workspace/messages/$channelId";
      path: "/messages/$channelId";
      fullPath: "/messages/$channelId";
      preLoaderRoute: typeof workspaceDotmessagesDotchannelIdRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/lenos/$": {
      id: "/_workspace/lenos/$";
      path: "/lenos/$";
      fullPath: "/lenos/$";
      preLoaderRoute: typeof workspaceDotlenosDotsplatRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/drafts/scheduled": {
      id: "/_workspace/drafts/scheduled";
      path: "/scheduled";
      fullPath: "/drafts/scheduled";
      preLoaderRoute: typeof workspaceDotdraftsDotscheduledRouteImport;
      parentRoute: typeof workspaceDotdraftsRoute;
    };
    "/_workspace/channels/$channelId": {
      id: "/_workspace/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof workspaceDotchannelsDotchannelIdRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/repos/$repoId/blob/$": {
      id: "/_workspace/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof workspaceDotreposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof workspaceRoute;
    };
    "/_workspace/channels/$channelId/posts/$postId": {
      id: "/_workspace/channels/$channelId/posts/$postId";
      path: "/channels/$channelId/posts/$postId";
      fullPath: "/channels/$channelId/posts/$postId";
      preLoaderRoute: typeof workspaceDotchannelsDotchannelIdDotpostsDotpostIdRouteImport;
      parentRoute: typeof workspaceRoute;
    };
  }
}

interface workspaceDotdraftsRouteChildren {
  workspaceDotdraftsDotscheduledRoute: typeof workspaceDotdraftsDotscheduledRoute;
  workspaceDotdraftsDotindexRoute: typeof workspaceDotdraftsDotindexRoute;
}

const workspaceDotdraftsRouteChildren: workspaceDotdraftsRouteChildren = {
  workspaceDotdraftsDotscheduledRoute: workspaceDotdraftsDotscheduledRoute,
  workspaceDotdraftsDotindexRoute: workspaceDotdraftsDotindexRoute,
};

const workspaceDotdraftsRouteWithChildren =
  workspaceDotdraftsRoute._addFileChildren(workspaceDotdraftsRouteChildren);

interface workspaceRouteChildren {
  workspaceDotagentsRoute: typeof workspaceDotagentsRoute;
  workspaceDotchannelsRoute: typeof workspaceDotchannelsRoute;
  workspaceDotdocumentsRoute: typeof workspaceDotdocumentsRoute;
  workspaceDotdraftsRoute: typeof workspaceDotdraftsRouteWithChildren;
  workspaceDothomeRoute: typeof workspaceDothomeRoute;
  workspaceDotmessagesRoute: typeof workspaceDotmessagesRoute;
  workspaceDotpeopleRoute: typeof workspaceDotpeopleRoute;
  workspaceDotpulseRoute: typeof workspaceDotpulseRoute;
  workspaceDotremindersRoute: typeof workspaceDotremindersRoute;
  workspaceDotreposRoute: typeof workspaceDotreposRoute;
  workspaceDotsavedRoute: typeof workspaceDotsavedRoute;
  workspaceDotworkflowsRoute: typeof workspaceDotworkflowsRoute;
  workspaceDotchannelsDotchannelIdRoute: typeof workspaceDotchannelsDotchannelIdRoute;
  workspaceDotlenosDotsplatRoute: typeof workspaceDotlenosDotsplatRoute;
  workspaceDotmessagesDotchannelIdRoute: typeof workspaceDotmessagesDotchannelIdRoute;
  workspaceDotmessagesDotnewRoute: typeof workspaceDotmessagesDotnewRoute;
  workspaceDotreposDotrepoIdRoute: typeof workspaceDotreposDotrepoIdRoute;
  workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute: typeof workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute;
  workspaceDotreposDotrepoIdDotblobDotsplatRoute: typeof workspaceDotreposDotrepoIdDotblobDotsplatRoute;
}

const workspaceRouteChildren: workspaceRouteChildren = {
  workspaceDotagentsRoute: workspaceDotagentsRoute,
  workspaceDotchannelsRoute: workspaceDotchannelsRoute,
  workspaceDotdocumentsRoute: workspaceDotdocumentsRoute,
  workspaceDotdraftsRoute: workspaceDotdraftsRouteWithChildren,
  workspaceDothomeRoute: workspaceDothomeRoute,
  workspaceDotmessagesRoute: workspaceDotmessagesRoute,
  workspaceDotpeopleRoute: workspaceDotpeopleRoute,
  workspaceDotpulseRoute: workspaceDotpulseRoute,
  workspaceDotremindersRoute: workspaceDotremindersRoute,
  workspaceDotreposRoute: workspaceDotreposRoute,
  workspaceDotsavedRoute: workspaceDotsavedRoute,
  workspaceDotworkflowsRoute: workspaceDotworkflowsRoute,
  workspaceDotchannelsDotchannelIdRoute: workspaceDotchannelsDotchannelIdRoute,
  workspaceDotlenosDotsplatRoute: workspaceDotlenosDotsplatRoute,
  workspaceDotmessagesDotchannelIdRoute: workspaceDotmessagesDotchannelIdRoute,
  workspaceDotmessagesDotnewRoute: workspaceDotmessagesDotnewRoute,
  workspaceDotreposDotrepoIdRoute: workspaceDotreposDotrepoIdRoute,
  workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute:
    workspaceDotchannelsDotchannelIdDotpostsDotpostIdRoute,
  workspaceDotreposDotrepoIdDotblobDotsplatRoute:
    workspaceDotreposDotrepoIdDotblobDotsplatRoute,
};

const workspaceRouteWithChildren = workspaceRoute._addFileChildren(
  workspaceRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  workspaceRoute: workspaceRouteWithChildren,
  inviteDotcodeRoute: inviteDotcodeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
