import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
    },
  },
  server: {
    port: parseInt(process.env.VITE_PORT || "5173", 10),
    strictPort: true,
    headers: {
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Embedder-Policy": "require-corp",
    },
  },
  preview: {
    headers: {
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Embedder-Policy": "require-corp",
    },
  },
  build: {
    rollupOptions: {
      input: {
        index: "index.html",
        "huddle-capture-processor":
          "src/features/huddle/worklets/huddle-capture-processor.js",
      },
      output: {
        entryFileNames: (chunk) =>
          chunk.name === "huddle-capture-processor"
            ? "assets/[name].js"
            : "assets/[name]-[hash].js",
        manualChunks(id) {
          if (
            id.includes("node_modules/prosemirror") ||
            id.includes("node_modules/@tiptap")
          ) {
            return "editor";
          }
          if (
            id.includes("node_modules/emoji-mart") ||
            id.includes("node_modules/@emoji-mart")
          ) {
            return "emoji";
          }
          if (
            id.includes("node_modules/nostr-tools") ||
            id.includes("node_modules/@noble")
          ) {
            return "nostr";
          }
          if (
            id.includes("node_modules/react-dom") ||
            id.includes("node_modules/react/")
          ) {
            return "react";
          }
        },
      },
    },
  },
});
